baseURL: /
languageCode: en-us
title: Josh Bradley | Marketer, Coder, Analyst
disableHugoGeneratorInject: true

params:
  author: Josh Bradley

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2

menu:
  main:
  - idenfifier: about
    name: About
    url: /about/
    weight: 1
  - idenfifier: contact
    name: Contact
    url: /contact/
    weight: 2
  - idenfifier: projects
    name: Projects
    url: /projects/
    weight: 3
  secondary:
  - idenfifier: categories
    name: Categories
    url: /categories/
    weight: 4
  - idenfifier: tags
    name: Tags
    url: /tags/
    weight: 5

deployment:
  targets:
    name: s3
    URL: s3://joshbradley.me?region=us-west-1
